# Đề thi Giữa kỳ Đại số tuyến tính cho Khoa học dữ liệu
## Khoa CNTT - trường ĐH Công nghiệp.
### Nhóm thực hành 1 & 2. Ngày 01/04/2022. Thời gian làm bài: 15h30' - 17h15'.

## Bài 1. (4 điểm)
Cho hai ma trận sau đây

$$A=\left( \begin{matrix}
   1 & 0 & 2 & a  \\
   1 & 2 & 4 & b  \\
   -1 & 2 & 0 & c  \\
   3 & -1 & 3 & d  \\
\end{matrix} \right), B=\left( \begin{matrix}
   4 & 5 & 1 & -2  \\
   0 & 1 & 2 & 1  \\
   0 & -2 & -3 & 1  \\
   a & b & c & d  \\
\end{matrix} \right)$$
trong đó $a,b,c,d$ là $4$ số cuối trong $MSSV$ (viết theo thứ tự từ trái sang phải). Khi làm bài, $SV$ chủ động thay các mã số đó vào đề bài trên.

In [1]:
import numpy as np 
from scipy import linalg

In [2]:
(a,b,c,d)=(8,5,2,1)
A= np.array([[1,0,2,a],[1,2,4,b],[-1,2,0,c],[3,-1,3,d]])
B= np.array([[4,5,1,-2],[0,1,2,1],[0,-2,-3,1],[a,b,c,d]])
A,B

(array([[ 1,  0,  2,  8],
        [ 1,  2,  4,  5],
        [-1,  2,  0,  2],
        [ 3, -1,  3,  1]]),
 array([[ 4,  5,  1, -2],
        [ 0,  1,  2,  1],
        [ 0, -2, -3,  1],
        [ 8,  5,  2,  1]]))

Bằng cách dùng các thư viện có hỗ trợ sẵn của Python, hãy thực hiện các yêu cầu sau:
* a) Tính $B+A$, $B{{A}^{T}}$, $2A-3B$.
* b) Tính $\det (A)$ , $\det ({{B}^{T}}+2I)$, $rank(AB).$ 
* c) Tính norm của vector hàng $1$ của $A,$ tính norm của vector cột $3$ của $B,$ tính tổng các phần tử trên đường chéo của $A.$
* d) Kiểm tra công thức ${{(AB)}^{T}}={{B}^{T}}{{A}^{T}}$ dựa trên hai ma trận đã cho.
* e) Sinh ngẫu nhiên một ma trận $C$ có kích thước $4\times 4$ với các phần tử là số nguyên trong miền từ $-9\to 9$, từ đó in ra các phần tử nằm phía dưới đường chéo của $A+BC.$ 

In [1]:
# a)
print(B+A)
print(B@(A.T))
print((2*A)-(3*B))
# b)
print("detA = ",linalg.det(A))
print("det(B^T+2I) = ",linalg.det(B.T+np.identity(4)))
print("rank(AB) = ",np.linalg.matrix_rank(A@B))
# c)
print("Norm của vector hàng 1 của A ",A[0,:], ": ",linalg.norm(A[0,:]))
print("Norm của vector cột 3 của B ",B[:,2]," : ",linalg.norm(B[:,2]))
print("Tổng các phần tử trên đường chéo A ",np.diag(A)," la :",sum(np.diag(A)))
# d)
print("(A*B)^T = \n",(A@B).T,"\n và B^T*A^T = \n",(B.T)@(A.T))
# Cách 1
if(((A@B).T).all()==((B.T)@(A.T)).all()):
    print("Công thức (𝐴𝐵)^𝑇=(𝐵^𝑇)*(𝐴^𝑇) là đúng ")
else : print("Công thức (𝐴𝐵)^𝑇=(𝐵^𝑇)*(𝐴^𝑇) là sai ")
## Cách 2
if np.allclose((A@B).T,(B.T)@(A.T)):
    print("Công thức (𝐴𝐵)^𝑇=(𝐵^𝑇)*(𝐴^𝑇) là đúng ")
else : print("Công thức (𝐴𝐵)^𝑇=(𝐵^𝑇)*(𝐴^𝑇) là sai ")
# e)
C= np.random.randint(-9,9,size=(4,4))
A+B@C,(np.tril(A+B@C))-np.diag(np.diag(A+B@C)),np.diag(A+B@C,k=-1)

NameError: name 'B' is not defined

## Bài 2. (2 điểm)
Kết quả học tập của một nhóm sinh viên ở môn Đại số tuyến tính cho Khoa học dữ liệu được cho trong bảng bên dưới. Sinh viên chỉ qua môn nếu điểm tổng kết không dưới $5.0$.

|Sinh viên | BT cá nhân  | Báo cáo   | Giữa kỳ   | Cuối kỳ   |
|----------|-------------|-----------|-----------|-----------|
|  A       |     8       |    7      |    6      |    4      |
|  B       |     0       |    7      |    5      |    6      |
|  C       |     3       |    9      |    4      |    5      |
|  D       |     7       |    8      |    3      |    5      |
|  E       |     10      |    10     |    10     |    9      |
|  F       |     6       |    0      |    6      |    5      |

Giảng viên đang cân nhắc cho các điểm theo trọng số nào để có lợi cho các sinh viên nhất (ít người rớt nhất), có $3$ phương án:
* $0.2, 0.2, 0.2, 0.4$.
* $0.1, 0.1, 0.3, 0.5.$
* $0.1, 0.2, 0.3, 0.4.$

Hãy giúp giảng viên lựa chọn phương án thích hợp.

In [4]:
M = np.array([[8,7,6,4],[0,7,5,6],[3,9,4,5],[7,8 ,3 ,5],[ 10,10,10,9],[6,0,6,5]])
N = np.array([[0.2, 0.2, 0.2, 0.4],[0.1, 0.1, 0.3, 0.5],[0.1, 0.2, 0.3, 0.4]])
print(N@(M.T))
result = (N@M.T<5)
print(result)
result.sum(axis=1)

[[5.8 4.8 5.2 5.6 9.6 4.4]
 [5.3 5.2 4.9 4.9 9.5 4.9]
 [5.6 5.3 5.3 5.2 9.6 4.4]]
[[False  True False False False  True]
 [False False  True  True False  True]
 [False False False False False  True]]


array([2, 3, 1])

2,3,1 là số sinh viên rớt ứng với mỗi phương án

## Bài 3. (2  điểm)
Cho bài toán sau, hãy bằng cách lập hệ phương trình thích hợp và giải bằng Python theo **ít nhất $2$ cách khác nhau**: <br>

Trong đợt dịch cúm Covid-19, sinh viên của một trường Đại học có nhận được trợ cấp từ nhà trường, từ địa phương và từ hội cựu sinh viên. Khảo sát trong một lớp học có ba nhóm: đang ở quê, đang ở trọ tại TPHCM và đang ở KTX trường. Biết rằng mức tiền hỗ trợ tiền:
* Của trường cho các nhóm trên lần lượt là: $200k, 600k, 400k$; 
* Của địa phương là: $500k, 500k, 500k$; 
* Của hội cựu sinh viên là: $0k, 700k, 300k.$

Biết rằng tổng tiền mà sinh viên được từ nhà trường là $37$ triệu, từ địa phương là $50$ triệu và từ hội cựu sinh viên là $29$ triệu. Tính tổng sinh viên của lớp.

In [65]:
A=np.array([[200,600,400],[500,500,500],[0,700,300]])
b=np.array([[37000],[50000],[29000]])
kq=linalg.solve(A,b) # cách 1
kq1=linalg.inv(A)@b # Cách 2 #A.I@b
# Cách 3 dùng sumpy (tham khảo lab1)
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
kq2=sp.solve([200*x+600*y+400*z-37000,500*x+500*y+500*z-50000,0*x+700*y+300*z-29000],[x,y,z])
kq,kq1,kq2

(array([[50.],
        [35.],
        [15.]]),
 array([[50.],
        [35.],
        [15.]]),
 {x: 50, y: 35, z: 15})

## Bài 4. (2 điểm)
Cho ma trận: $M=\left( \begin{matrix}
   2 & a & -2  \\
   0 & 3 & 0  \\
   0 & 0 & 3  \\
\end{matrix} \right)$ trong đó $a$ là tham số thực.
* a) Cho $a=1,$ hãy chéo hóa ma trận này để thu được ma trận $D$ bằng cách dùng thư viện của Python và kiểm chứng lại bằng việc tính toán từng bước để tìm đa thức đặc trưng và các giá trị riêng của $M$. Từ đó hãy nêu cách tính ${{M}^{99}}$.
* b) Ma trận chéo hóa $D$ của $M$ luôn không đổi với mọi giá trị $a$ tùy ý, hãy kiểm chứng với vài giá trị cụ thể của $a$ và giải thích lý do.


In [34]:
a=1
M=Matrix([[2,a,-2],[0,3,0],[0,0,3]])
print(M)
M

Matrix([[2, 1, -2], [0, 3, 0], [0, 0, 3]])


Matrix([
[2, 1, -2],
[0, 3,  0],
[0, 0,  3]])

In [35]:
I = np.identity(3)
P,D = M.diagonalize()
I,P,D

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 Matrix([
 [1, 1, -2],
 [0, 1,  0],
 [0, 0,  1]]),
 Matrix([
 [2, 0, 0],
 [0, 3, 0],
 [0, 0, 3]]))

In [40]:
x=Symbol('x')
det(M-x*I)

-1.0*x**3 + 8.0*x**2 - 21.0*x + 18

In [41]:
f=solve([det(M-x*I)],[x])
f

[(2.00000000000000,), (3.00000000000000,)]

Để tính $M^{99}$: <BR>
Ta lấy: $$M=PDP^{-1}\rightarrow M^{99}=PD^{99}P^{-1}$$ <br>


b) kiểm chứng với vài giá trị   
Vì nó là ma trận tam giác trên 

a)    
D=ma tran duong cheo
Khai bao M   
P,D=M.diagonalize() -> in D     
M=P^-1DP   
b) Kiem chung: thu nhieu gia tri, in ra   
    giai thich: ma tran tam giac tren, det=tich duong cheo co tinh chat dac biet     
        tinh det ko anh huong det, vecto rieng, tri rieng