# Đề thi Giữa kỳ Đại số tuyến tính trong Khoa học dữ liệu
## Khoa CNTT - IUH. Học kỳ 2 năm học 2022-2023.
> Thời gian làm bài: 90 phút (sinh viên được dùng tài liệu chuẩn bị sẵn & Internet). SV export ra một file HTLM và nén lại cùng với file notebook rồi nộp.

In [3]:
import numpy as np
from scipy import linalg
from sympy import *

### Bài 1. (3 điểm) $-$ các thao tác cơ bản trên ma trận

Cho các ma trận sau đây: 
$$A=\left( \begin{matrix}
   a & 2 & 1 & 5  \\
   0 & b & 0 & 4  \\
   -1 & 4 & c & 1  \\
   2 & -1 & 3 & d  \\
\end{matrix} \right) \text{ và } B=\left( \begin{matrix}
   3 & 5 & 1 & a  \\
   0 & 3 & b & 2  \\
   0 & c & 1 & 1  \\
   d & -1 & -3 & 0  \\
\end{matrix} \right),$$
trong đó $a,b,c,d$ là $4$ số cuối trong MSSV (thứ tự từ trái sang phải). Khi làm bài, SV tự thay các số đó vào đề bài trên. Ví dụ: $21099581$ thì $a=9,b=5,c=8,d=1$ (chú ý viết cẩn thận, nếu sai MSSV thì không tính điểm bài này).

Bằng các dùng các thư viện có hỗ trợ sẵn của Python, hãy thực hiện các yêu cầu sau:

In [12]:
a,b,c,d=8,5,2,1
A = np.array([[a,2,1,5],[0,b,0,4],[-1,4,c,1],[2,-1,3,d]])
B = np.array([[3,5,1,a],[0,3,b,2],[0,c,1,1],[d,-1,-3,0]])
A,B

(array([[ 8,  2,  1,  5],
        [ 0,  5,  0,  4],
        [-1,  4,  2,  1],
        [ 2, -1,  3,  1]]),
 array([[ 3,  5,  1,  8],
        [ 0,  3,  5,  2],
        [ 0,  2,  1,  1],
        [ 1, -1, -3,  0]]))

a) Tính $B \cdot {{A}^{T}}$, $3A-4B$.

In [16]:
print("B*(A^T) =  \n",B@(A.T))
print("\n3A-4B = \n",3*A-4*B)

B*(A^T) =  
 [[ 75  57  27  12]
 [ 21  23  24  14]
 [ 10  14  11   2]
 [  3  -5 -11  -6]]

3A-4B = 
 [[ 12 -14  -1 -17]
 [  0   3 -20   4]
 [ -3   4   2  -1]
 [  2   1  21   3]]


b) Tính $\det (A+2I)$ và $rank({{B}^{2}}).$ 

In [19]:
print("det(A+2*I) = ",linalg.det(A+2*np.identity(4)))
print("rank(B^2) = ",np.linalg.matrix_rank(B@B))

det(A+2*I) =  980.0
rank(B^2) =  4


c) Tính độ dài của vector cột $2$ của $A$ và tổng các phần tử trên đường chéo của $A+B.$  

In [21]:
print("Norm của vector cột 2 của A ",A[:,1]," : ",linalg.norm(A[:,1]))
print("Tổng các phần tử trên đường chéo A+B ",np.diag(A+B)," la :",sum(np.diag(A+B)))

Norm của vector cột 2 của A  [ 2  5  4 -1]  :  6.782329983125268
Tổng các phần tử trên đường chéo A+B  [11  8  3  1]  la : 23


d) Sinh ngẫu nhiên một ma trận $C$ có kích thước $4\times 4$ với các phần tử là số nguyên trong miền từ $-10\to 10$, từ đó in ra ma trận tam giác trên tạo thành từ $CA+B.$ 

In [27]:
C= np.random.randint(-10,10,size=(4,4))
print("C@A+B = \n",C@A+B)
print("Ma tran tam giac tren : \n",np.triu(C@A+B))

C@A+B = 
 [[-46 -27  15 -39]
 [ 96  28  29  82]
 [-62 -53  -3 -53]
 [ 49  32  21  48]]
Ma tran tam giac tren : 
 [[-46 -27  15 -39]
 [  0  28  29  82]
 [  0   0  -3 -53]
 [  0   0   0  48]]


e) Kiểm chứng tính chất kết hợp của phép nhân trên các ma trận $A,B,C$ đã cho: $(AB)C = A(BC)$.

In [29]:
if np.allclose((A@B)@C , A@(B@C)):
    print("Công thức (𝐴𝐵)C = A(BC) là đúng ")
else : print("Công thức (𝐴𝐵)C = A(BC) là sai ")

Công thức (𝐴𝐵)C = A(BC) là đúng 


### Bài 2. (2 điểm) $-$ giải hệ phương trình
Để mở rộng sản suất, một công ty đã vay $800$ triệu đồng từ ba ngân hàng $D, E$ và $F$, với lãi suất cho vay theo năm lần lượt là $6\%, 8\%$ và $9\%$. Biết rằng tổng số tiền lãi năm đầu tiên công ty phải trả cho ba ngân hàng là $60$ triệu đồng và số tiền lãi công ty trả cho hai ngân hàng $D$ và $F$ là bằng nhau.

a) Gọi $x_1,x_2,x_3$ là số tiền mà công ty đã vay từ 3 ngân hàng $D,E,F$ và đặt $X=\begin{bmatrix} x_1 & x_2 & x_3 \end{bmatrix}^T$. Mô hình hoá bài toán trên dưới dạng hệ phương trình tuyến tính $AX=b$, bằng cách tìm ma trận $A$ và vector $b$.

In [66]:
A = np.array([[0.06,0.08,0.09],[1,1,1],[1,0,-1]])
b=np.array([[60],[800],[0]])
A,b

(array([[ 0.06,  0.08,  0.09],
        [ 1.  ,  1.  ,  1.  ],
        [ 1.  ,  0.  , -1.  ]]),
 array([[ 60],
        [800],
        [  0]]))

b) Tính số tiền mà công ty đã vay từ $3$ ngân hàng bằng ít nhất *hai cách*.

In [91]:
kq=linalg.solve(A,b) #Cách 1
kq1=linalg.inv(A)@b #Cách 2
kq,kq1

(array([[4.00000000e+02],
        [3.41060513e-13],
        [4.00000000e+02]]),
 array([[4.00000000e+02],
        [4.54747351e-13],
        [4.00000000e+02]]))

In [85]:
kq1=linalg.inv(A)@b
kq1

array([[4.00000000e+02],
       [4.54747351e-13],
       [4.00000000e+02]])

Làm tròn các số của ma trận kq1 thì ta được ma trận :
$$ kq1 = \begin{bmatrix}
400\\ 
0\\ 
400
\end{bmatrix} $$

In [92]:
# Cách 3 dùng sumpy
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
kq2=sp.solve([0.06*x+0.08*y+0.09*z-60,x+y+z-800,x-z],[x,y,z])
kq2

{x: 400.000000000000, y: 0.0, z: 400.000000000000}

Vậy số tiền mà công ty đã vay từ 3 ngân hàng $D,E,F$ lần lượt là 400 triệu , 0 triệu , 400 triệu

### Bài 3. (1 đ) $-$ thao tác trên vector

Trong lĩnh vực xử lý ngôn ngữ tự nhiên $NLP$, với danh sách từ vựng $\mathcal{L}$ độ dài $\ell$, mỗi câu văn có thể được mô tả bởi vector $v\in\mathbb{R}^{\ell}$ mà thành phần thứ $i$ cho biết số lần mà từ $d_i \in \mathcal{L}$ xuất hiện trong câu. Vector đó còn được gọi là tọa độ của câu văn trong $\mathcal{L}$. Xét các câu văn sau đây (bỏ qua các dấu câu):
> * $D_1$: *tôi là Kỳ*.
> * $D_2$: *tôi thích đi xem phim*.
> * $D_3$: *Kỳ rất thích xem tôi du lịch*.
> * $D_4$: *tôi rất rất thích đi du lịch, Kỳ là tên tôi*.

Giả sử rằng $\mathcal{L} =$ (*Kỳ, du, đi, là, lịch, phim, rất, tên, thích, tôi, xem*) với $|\mathcal{L}| = 11$ thì chẳng hạn câu văn $D_0$ = *tôi rất thích phim Kỳ Kỳ* sẽ có tọa độ là $$d_0 = (2,0,0,0,0,1,1,0,1,1,0).$$

a) Viết toạ độ của các câu văn $D_1,D_2,D_3,D_4$ ở dạng vector trong không gian $11$ chiều ứng với từ vựng $\mathcal{L}$.

b) Tính khoảng cách Euclid đôi một giữa các câu văn trên, làm tròn $2$ chữ số thập phân.

In [94]:
L=['Kỳ', 'du', 'đi', 'là', 'lịch', 'phim', 'rất', 'tên', 'thích', 'tôi', 'xem']
L.index('Kỳ')

ValueError: 'Kỳ' is not in list

In [99]:
# code mẫu tham khảo
import numpy as np
d1 = np.array([1,0,0,1,0,0,0,0,0,1,0])
d2 = np.array([0,0,1,0,0,1,0,0,1,1,1])
d3 = np.array([1,1,0,0,1,0,1,0,1,1,1])
d4 = np.array([1,1,1,1,1,0,2,1,1,2,0])
D = np.vstack([d1,d2,d3,d4])
l = len(D)
for i in range(0,l):
    for j in range(0,l):
        print('Khoảng cách giữa d{} & d{} là'.format(i+1,j+1), round(np.linalg.norm(D[i]-D[j]), 2))

Khoảng cách giữa d1 & d1 là 0.0
Khoảng cách giữa d1 & d2 là 2.45
Khoảng cách giữa d1 & d3 là 2.45
Khoảng cách giữa d1 & d4 là 3.16
Khoảng cách giữa d2 & d1 là 2.45
Khoảng cách giữa d2 & d2 là 0.0
Khoảng cách giữa d2 & d3 là 2.45
Khoảng cách giữa d2 & d4 là 3.46
Khoảng cách giữa d3 & d1 là 2.45
Khoảng cách giữa d3 & d2 là 2.45
Khoảng cách giữa d3 & d3 là 0.0
Khoảng cách giữa d3 & d4 là 2.45
Khoảng cách giữa d4 & d1 là 3.16
Khoảng cách giữa d4 & d2 là 3.46
Khoảng cách giữa d4 & d3 là 2.45
Khoảng cách giữa d4 & d4 là 0.0


### Bài 4. (2.5 điểm) $-$ phân rã QR
Cho ma trận $A$ được xác định bởi $$A=\begin{bmatrix} 
1 & 1 & -1\\
0 & 1 & 2\\
1 & 1 & 1
\end{bmatrix}.$$
Tìm hai ma trận $Q$ và $R$ thoả mãn $A=QR$, biết $Q$ là ma trận gồm các vector cột trực chuẩn và $R$ là ma trận tam giác trên khả nghịch. SV tính toán từng bước sau đó sử dụng thư viện để kiểm chứng lại.

In [ ]:
#thực hiện từng bước theo sơ đồ sau đây

**Bước 1.** Các vector cột của $A$ là:
$$u_1 = [1,0,1 ]^T, \, u_2 = [1,1,1]^T, \, u_3 = [ -1,2,1 ]^T.$$

In [140]:
u1 = np.array([1,0,1])
u2 = np.array([1,1,1])
u3 = np.array([-1,2,1])
u1,u2,u3

(array([1, 0, 1]), array([1, 1, 1]), array([-1,  2,  1]))

**Bước 2.** Trực giao hóa họ các vector bằng thuật giải Gram-Schmidt (để thuận tiện, ta viết vector theo dòng)

$$v_1 = u_1 = (1, 0, 1),$$
$$\left\| v_1 \right\|^2 = 2 $$
$$\left\langle u_2,v_1 \right\rangle = 2$$
$$v_2 = u_2 - \frac{\left\langle u_2,v_1 \right\rangle}{\left\| v_1 \right\|^2} v_1 = (0, 1, 0),$$
$$\left\| v_2 \right\|^2 = 1 $$
$$\left\langle u_3,v_1 \right\rangle = 0 $$
$$\left\langle u_3,v_2 \right\rangle = 2 $$
$$v_3 = u_3 - \frac{\left\langle u_3,v_1 \right\rangle}{\left\| v_1 \right\|^2} v_1 - \frac{\left\langle u_3,v_2 \right\rangle}{\left\| v_2 \right\|^2} v_2 = (-1,  0,  1) $$
$$\left\| v_3 \right\|^2 = 2  $$

Kết luận họ trực giao là:
$$v_1 = (1, 0, 1) , v_2 = (0, 1, 0) , v_3 = (-1,  0,  1).$$

**Bước 3.** Tìm ma trận $Q$: chuẩn hóa họ các vector ở trên, ta được
$$q_1 = \frac{v_1}{\left\| v_1 \right\|} = \frac{1}{\sqrt{2}}(1,0,1) ,$$
$$q_2 = \frac{v_2}{\left\| v_2 \right\|} = (0,1,0) $$
$$q_3 = \frac{v_3}{\left\| v_3 \right\|} = \frac{1}{\sqrt{2}}(−1,0,1)$$

Từ đó có ma trận $Q$ là:
$$Q=\left[ \begin{matrix}
   {{q}_{1}} & {{q}_{2}} & {{q}_{3}}  \\
\end{matrix} \right]=\left[ \begin{matrix}
{\frac{1}{\sqrt{2}}} & 0 & {\frac{-1}{\sqrt{2}}} \\ 
0 & 1 & 0\\ 
{\frac{1}{\sqrt{2}}} & 0 & {\frac{1}{\sqrt{2}}}
\end{matrix} \right]$$

**Bước 4.** Tìm ma trận $R$: ta tính các tích vô hướng sau đây
$$\left\langle {{u}_{1}},{{q}_{1}} \right\rangle = \sqrt{2}, $$
$$\left\langle {{u}_{2}},{{q}_{1}} \right\rangle = \sqrt{2}, $$
$$\left\langle {{u}_{3}},{{q}_{1}} \right\rangle = 0, $$
$$\left\langle {{u}_{2}},{{q}_{2}} \right\rangle = \frac{1}{\sqrt{2}}, $$
$$\left\langle {{u}_{3}},{{q}_{2}} \right\rangle = \sqrt{2}, $$
$$\left\langle {{u}_{3}},{{q}_{3}} \right\rangle = \sqrt{2}, $$

Từ đó ta có ma trận $R$ là:

$$R=\left[ \begin{matrix}
   \left\langle {{u}_{1}},{{q}_{1}} \right\rangle  & \left\langle {{u}_{2}},{{q}_{1}} \right\rangle  & \left\langle {{u}_{3}},{{q}_{1}} \right\rangle   \\
   0 & \left\langle {{u}_{2}},{{q}_{2}} \right\rangle  & \left\langle {{u}_{3}},{{q}_{2}} \right\rangle   \\
   0 & 0 & \left\langle {{u}_{3}},{{q}_{3}} \right\rangle   \\
\end{matrix} \right]=\left[ \begin{matrix}
   {\sqrt{2}} & {\sqrt{2}} & { 0}  \\
   {0} & {\frac{1}{\sqrt{2}}} & {\sqrt{2}}  \\
   {0} & {0} & {\sqrt{2}}  \\
\end{matrix} \right]$$

In [168]:
#code mẫu tham khảo dùng thư viện
import numpy as np
A = np.array([[1,1,-1],[0 ,1 , 2],[1 , 1 , 1]]) 
Q, R =  linalg.qr(A)
(Q, R),Q@R

((array([[-7.07106781e-01, -3.35470445e-17, -7.07106781e-01],
         [-0.00000000e+00, -1.00000000e+00,  4.74426853e-17],
         [-7.07106781e-01,  3.35470445e-17,  7.07106781e-01]]),
  array([[-1.41421356e+00, -1.41421356e+00, -3.33066907e-16],
         [ 0.00000000e+00, -1.00000000e+00, -2.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  1.41421356e+00]])),
 array([[ 1.,  1., -1.],
        [ 0.,  1.,  2.],
        [ 1.,  1.,  1.]]))

$$ (-7.07106781e-01) = \frac{-1}{\sqrt{2}} $$

### Bài 5. (1.5 điểm) $-$ trị riêng, vector riêng

Cho $A$ là ma trận vuông cấp $2023$ và cho $x=\begin{bmatrix} 1 & 2 & 3& \ldots & 2023 \end{bmatrix}^T$ là một vector riêng của $A$ ứng với giá trị riêng là $\lambda =1$.	

a) Tính $Ax$.

$Av=\lambda v$

In [ ]:
A.dot(x)

b) Tìm một giá trị riêng của ma trận $A^{2023}$ (có giải thích).

c) Ta biết rằng việc chéo hóa ma trận được dùng để tính lũy thừa ma trận. Vậy lũy thừa ma trận có những ứng dụng vào các bài toán nào?

Tính giá trị riêng , vecto riêng